import React from 'react';
import { cookies } from 'next/headers';
import './globals.css';

export const dynamic = 'force-dynamic'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log('RootLayout: Starting to render');
  const cookieStore = await cookies();
  const onboarded = cookieStore.get('onboarded');
  console.log(`RootLayout: Onboarded status: ${onboarded?.value}`);

  console.log('RootLayout: Rendering children');
  try {
    return (
      <html lang="en">
        <body>{children}</body>
      </html>
    );
  } finally {
    console.log('RootLayout: Render complete');
  }
}
